import 'newrelic';
import * as bodyParser from 'body-parser';
import * as cors from 'cors';
import * as express from 'express';
import * as helmet from 'helmet';
import * as morgan from 'morgan';
import 'reflect-metadata';
import * as swaggerJSDoc from 'swagger-jsdoc';
import * as swaggerStats from 'swagger-stats';
import * as swaggerUi from 'swagger-ui-express';
import {createConnection} from 'typeorm';
import config from './config/config';
import routes from './routes';
import logger from './utils/logger';

declare const process: any;

const options = {
  swaggerDefinition: {
    // Like the one described here: https://swagger.io/specification/#infoObject
    info: {
      title: 'Test API',
      version: '1.0.0',
      description: 'Test Express API with autogenerated swagger doc',
    },
  },
  // List of files to be processes. You can also set globs './routes/*.js'
  apis: ['**/routes/auth.ts', '**/controller/Admin/*.ts'],
};

const specs = swaggerJSDoc(options);
// Connects to the Database -> then starts the express
createConnection()
  .then(() => {
    if (!config.jwtSecret) {
      throw new Error('Missing required environment variable: JWT_SECRET');
    }

    const app = express();
    app.disable('x-powered-by');

    // Support commas for multiple origins, or fall back to localhost during development
    const allowedOrigins = process.env.ALLOWED_ORIGINS
      ? process.env.ALLOWED_ORIGINS.split(',')
          .map((origin: string) => origin.trim())
          .filter(Boolean)
      : ['http://localhost', 'http://localhost:80', 'http://localhost:8080'];

    app.use(
      cors({
        origin: allowedOrigins,
        methods: ['GET', 'HEAD', 'PUT', 'PATCH', 'POST', 'DELETE', 'OPTIONS'],
        credentials: true,
        allowedHeaders: ['Content-Type', 'Accept', 'Authorization', 'auth'],
      }),
    );

    app.use(swaggerStats.getMiddleware({}));
    app.use(helmet());
    app.use(bodyParser.json());
    app.use(morgan('combined'));
    const apiPort = Number(process.env.API_INTERNAL_PORT || 3001);
    app.get('/health', (_req, res) => {
      res.status(200).send({status: 'ok'});
    });
    app.get('/api/health', (_req, res) => {
      res.status(200).send({status: 'ok'});
    });
    // Set all routes from routes folder
    app.use('/', routes);
    app.use('/api-docs', swaggerUi.serve, swaggerUi.setup(specs));
    app.listen(apiPort, async () => {
      logger.info({ port: apiPort }, 'API server is ready');
    });
  })
  .catch((err) => {
    logger.error({ err }, 'Failed to start API server');
    process.exit(1);
  });
